### ISSUE TITLE
Migrations with custom provider don't work properly

### ISSUE THREAD

**Issue by HerrRomich** [kysely-org/kysely#1097]
If the migrator is created with the custom MigrationProvider, that delivers a record of class instances, the migration fails.

```
export interface XchangeMigration extends Migration {
  readonly name: string;
}
```

```
@injectable()
export class XchangeMigrationProvider implements MigrationProvider {
  constructor(@multiInject(MIGRATION) private readonly migrations: XchangeMigration[]) {}
  async getMigrations(): Promise<Record<string, Migration>> {
    const migrations = this.migrations.reduce(
      (prev, curr) => {
        prev[curr.key] = curr;
        return prev;
      },
      {} as Record<string, Migration>
    );
    return migrations;
  }
}

```
```
@injectable()
export class XchangeMigrationService {
  constructor(
    @inject(DB) private readonly db: DB,
    private readonly migrationProvider: XchangeMigrationProvider
  ) {}

  async migrateUp() {
    await this.createMigrator().migrateToLatest();
  }

  private createMigrator(): Migrator {
    return new Migrator({
      db: this.db,
      provider: this.migrationProvider,
    });
  }
}
```

```
TypeError: migration.up is not a function
    at #migrateUp (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/migration/migrator.js:479:33)
    at run (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/migration/migrator.js:352:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/kysely.js:418:32
    at async DefaultConnectionProvider.provideConnection (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async #migrate (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/migration/migrator.js:199:20)
    at async XchangeMigrationService.migrateUp (/Users/romansmushkevich/Dev/xchange/packages/xchange-backend/dist/index.cjs:1227:9)
    at async XchangeStartupService.startup (/Users/romansmushkevich/Dev/xchange/packages/xchange-backend/dist/index.cjs:1512:9)
    at async eval (webpack-internal:///./src/platform/index.ts:56:51)
```

I suppose, that the problem is in a spread operator, that is used in method 
#resolveMigrations. Unfortunately it doesn't copy the up method of instance of Migration class.

**Comment by HerrRomich** [comment]
There is a workaround for the problem:

```
@injectable()
export class XchangeMigrationProvider implements MigrationProvider {
  constructor(@multiInject(MIGRATION) private readonly migrations: XchangeMigration[]) {}
  async getMigrations(): Promise<Record<string, Migration>> {
    const migrations = this.migrations.reduce(
      (prev, curr) => {
        const migration: Migration = {
          up: async (db: Kysely<DB>): Promise<void> => {
            await curr.up(db);
          },
        };
        const downMethod = curr.down;
        if (downMethod) {
          migration.down = async (db: Kysely<DB>): Promise<void> => {
            await downMethod(db);
          };
        }
        prev[curr.name] = migration;
        return prev;
      },
      {} as Record<string, Migration>
    );
    return migrations;
  }
}
```

But I would like to have a proper solution.
Thank you

**Comment by koskimas** [comment]
🤦

**Comment by koskimas** [comment]
Your migrations must have an up method. How would they otherwise do anything? You class says it implement's the migration interface but it actually doesn't. That code should not compile.
