### ISSUE TITLE
Migrations with custom provider don't work properly if Migrations are instances of classes, implementing Migration interface.

### ISSUE THREAD

**Issue by HerrRomich** [kysely-org/kysely#1098]
If the migrator is created with the custom MigrationProvider, that delivers a record of class instances, the migration fails.

This interface is suited for defining a list of migrations as services to be injected as list into custom migration provider:
```
export interface XchangeMigration extends Migration {
  readonly name: string;
}
```

Custom migration provider injects a list of in IoC container registered custom migrations:
```
@injectable()
export class XchangeMigrationProvider implements MigrationProvider {
  constructor(@multiInject(MIGRATION) private readonly migrations: XchangeMigration[]) {}
  async getMigrations(): Promise<Record<string, Migration>> {
    const migrations = this.migrations.reduce(
      (prev, curr) => {
        prev[curr.key] = curr;
        return prev;
      },
      {} as Record<string, Migration>
    );
    return migrations;
  }
}
```

Custom migration service injects custom migration provider and starts migration:
```
@injectable()
export class XchangeMigrationService {
  constructor(
    @inject(DB) private readonly db: DB,
    private readonly migrationProvider: XchangeMigrationProvider
  ) {}

  async migrateUp() {
    await this.createMigrator().migrateToLatest();
  }

  private createMigrator(): Migrator {
    return new Migrator({
      db: this.db,
      provider: this.migrationProvider,
    });
  }
}
```

Custom migration implements extended Kysely Migration interface and defines "up" method.
```
@injectable()
export class InitialMigration implements XchangeMigration {
  name = '2024-06-01T12:00:00.initial.migration';

  async up(db: Kysely<unknown>): Promise<void> {
    await db.schema
      .createTable('releaseGroup')
      .addColumn('id', 'serial', (builder) => builder.notNull())
      .addColumn('name', 'varchar(75)', (builder) => builder.notNull())
      .addColumn('description', 'varchar(200)')
      .addColumn('artifactType', 'varchar(50)', (builder) => builder.notNull())
      .addColumn('artifactName', 'varchar(50)', (builder) => builder.notNull())
      .addColumn('owners', sql`varchar[]`, (builder) => builder.notNull())
      .addColumn('createdAt', 'timestamp', (builder) => builder.notNull())
      .addColumn('createdBy', 'varchar(50)', (builder) => builder.notNull())
      .addColumn('modifiedAt', 'timestamp')
      .addColumn('modifiedBy', 'varchar(50)')
      .addPrimaryKeyConstraint('release_group_pk', ['id'])
      .addUniqueConstraint('release_group_name_uq', ['name'])
      .execute();
  }
}
```

When a migration is called it fails with an exception:
```
TypeError: migration.up is not a function
    at #migrateUp (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/migration/migrator.js:479:33)
    at run (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/migration/migrator.js:352:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/kysely.js:418:32
    at async DefaultConnectionProvider.provideConnection (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async #migrate (/Users/romansmushkevich/Dev/xchange/node_modules/kysely/dist/cjs/migration/migrator.js:199:20)
    at async XchangeMigrationService.migrateUp (/Users/romansmushkevich/Dev/xchange/packages/xchange-backend/dist/index.cjs:1227:9)
    at async XchangeStartupService.startup (/Users/romansmushkevich/Dev/xchange/packages/xchange-backend/dist/index.cjs:1512:9)
    at async eval (webpack-internal:///./src/platform/index.ts:56:51)
```

I suppose, that the problem is in a spread operator, that is used in method
#resolveMigrations. Unfortunately it doesn't copy the up method of instance of Migration class.

**Comment by igalklebanov** [comment]
Hey 👋

What the Java is all of this over-engineering?

Don't. Keep it simple.
