### ISSUE TITLE
Failing Migration 

### ISSUE THREAD

**Issue by HendrixString** [kysely-org/kysely#1108]
Hi there,

So, I wrote dialect for `cloudflare D1`

During, the start of the migration, at the third command that kysely issues, i get:

```js
{
  "sql": "select \"name\", \"type\", \"notnull\", \"dflt_value\" from pragma_table_info(?) as \"table_info\" order by \"cid\"",
  "params": [
    "_cf_KV"
  ]
}
{
  "result": [],
  "success": false,
  "errors": [
    {
      "code": 7500,
      "message": "not authorized: SQLITE_AUTH"
    }
  ],
  "messages": []
}
failed to migrate
Error: [object Object]
    at D1Connection._internal_execute (file:///Users/tomeriko/hendrix/store-craft/packages/database-cloudflare-d1/kysely.d1.dialect.js:197:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
    at async DefaultConnectionProvider.provideConnection (file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
    at async DefaultQueryExecutor.executeQuery (file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
    at async SelectQueryBuilderImpl.execute (file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/query-builder/select-query-builder.js:295:24)
    at async #getTableMetadata (file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/dialect/sqlite/sqlite-introspector.js:50:25)
    at async Promise.all (index 0)
    at async #doesTableExists (file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/migration/migrator.js:314:24)
    at async #ensureMigrationTableExists (file:///Users/tomeriko/hendrix/store-craft/node_modules/kysely/dist/esm/migration/migrator.js:250:15)

```

**Comment by koskimas** [comment]
There's a discord server that's better suited for this many questions.
