### ISSUE TITLE
AlterTableBuilder add index fails

### ISSUE THREAD

**Issue by armpogart** [kysely-org/kysely#1121]
`AlterTableBuilder`s `addIndex` method fails to run the migration.

Kysely version: **0.27.4** (tried also on **0.27.3** and without success)
PostgresDB version: **16.3**

The failing example is below. The strange thing is that this migration worked without any problems during the development while running dev build (using `Nest JS`, not sure how their dev build with watcher is different from usual build), but it failed after deploying on staging and running usual build. Now I can't even reproduce running the migration without problems with dev build.

`CreateIndexBuilder` works without problems (see the migration at the end). If the `AlterTableBuilder`s `addIndex` is not supposed to be used with `Postgres` driver, I couldn't find that information in the documentation anywhere.

You can also see the full error stack below.

```typescript
import { Kysely } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .createTable('user_groups')
    .addColumn('group_id', 'bigint', (column) =>
      column.references('groups.id').onDelete('cascade').onUpdate('cascade').notNull(),
    )
    .addColumn('user_id', 'int4', (column) =>
      column.references('users.id').onDelete('cascade').onUpdate('cascade').notNull(),
    )
    .addPrimaryKeyConstraint('user_groups_pkey', ['user_id', 'group_id'])
    .execute();

  await db.schema.alterTable('user_groups').addIndex('group_id_idx').column('group_id').execute();
  await db.schema.alterTable('user_groups').addIndex('user_id_idx').column('user_id').execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('user_groups').execute();
}
```

The resulting js is:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.down = exports.up = void 0;
async function up(db) {
    await db.schema
        .createTable('user_groups')
        .addColumn('group_id', 'bigint', (column) => column.references('groups.id').onDelete('cascade').onUpdate('cascade').notNull())
        .addColumn('user_id', 'int4', (column) => column.references('users.id').onDelete('cascade').onUpdate('cascade').notNull())
        .addPrimaryKeyConstraint('user_groups_pkey', ['user_id', 'group_id'])
        .execute();
    await db.schema.alterTable('user_groups').addIndex('group_id_idx').column('group_id').execute();
    await db.schema.alterTable('user_groups').addIndex('user_id_idx').column('user_id').execute();
}
exports.up = up;
async function down(db) {
    await db.schema.dropTable('user_groups').execute();
}
exports.down = down;
//# sourceMappingURL=20240814143216_add_user_group_junction.js.map
```

Error:

```bash
Failed to run.
error: type "group_id_idx" does not exist
    at PROJECT\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresConnection.executeQuery (PROJECT\node_modules\kysely\dist\cjs\dialect\postgres\postgres-driver.js:72:28)
    at async PROJECT\node_modules\kysely\dist\cjs\query-executor\query-executor-base.js:37:28
    at async #run (PROJECT\node_modules\kysely\dist\cjs\driver\single-connection-provider.js:26:16)
    at async DefaultQueryExecutor.executeQuery (PROJECT\node_modules\kysely\dist\cjs\query-executor\query-executor-base.js:36:16)
    at async AlterTableAddIndexBuilder.execute (PROJECT\node_modules\kysely\dist\cjs\schema\alter-table-add-index-builder.js:146:9)
    at async Object.up (PROJECT\dist\db\migrations\20240814143216_add_user_group_junction.js:11:5)
    at async #migrateUp (PROJECT\node_modules\kysely\dist\cjs\migration\migrator.js:479:17)
    at async run (PROJECT\node_modules\kysely\dist\cjs\migration\migrator.js:352:28)
    at PostgresConnection.executeQuery (PROJECT\node_modules\kysely\dist\cjs\dialect\postgres\postgres-driver.js:92:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PROJECT\node_modules\kysely\dist\cjs\query-executor\query-executor-base.js:37:28
    at async #run (PROJECT\node_modules\kysely\dist\cjs\driver\single-connection-provider.js:26:16)
    at async DefaultQueryExecutor.executeQuery (PROJECT\node_modules\kysely\dist\cjs\query-executor\query-executor-base.js:36:16)
    at async AlterTableAddIndexBuilder.execute (PROJECT\node_modules\kysely\dist\cjs\schema\alter-table-add-index-builder.js:146:9)
    at async Object.up (PROJECT\dist\db\migrations\20240814143216_add_user_group_junction.js:11:5)
    at async #migrateUp (PROJECT\node_modules\kysely\dist\cjs\migration\migrator.js:479:17)
    at async run (PROJECT\node_modules\kysely\dist\cjs\migration\migrator.js:352:28)
    at async PROJECT\node_modules\kysely\dist\cjs\kysely.js:418:32 {
  length: 99,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: '46',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '274',
  routine: 'typenameType'
}
```

Working one:

```typescript
import { Kysely } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .createTable('user_groups')
    .addColumn('group_id', 'bigint', (column) =>
      column.references('groups.id').onDelete('cascade').onUpdate('cascade').notNull(),
    )
    .addColumn('user_id', 'int4', (column) =>
      column.references('users.id').onDelete('cascade').onUpdate('cascade').notNull(),
    )
    .addPrimaryKeyConstraint('user_groups_pkey', ['user_id', 'group_id'])
    .execute();

  await db.schema.createIndex('group_id_idx').on('user_groups').column('group_id').execute();
  await db.schema.createIndex('user_id_idx').on('user_groups').column('user_id').execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('user_groups').execute();
}
```

**Comment by igalklebanov** [comment]
Hey 👋 

PostgreSQL doesn't support adding an index in `ALTER TABLE` queries. Kysely only writes the SQL you tell it.

**Comment by armpogart** [comment]
> Hey 👋 
> 
> PostgreSQL doesn't support adding an index in `ALTER TABLE` queries. Kysely only writes the SQL you tell it to. Bring your own SQL knowledge.

Thanks, I've missed that part when working with kysely and thought it will abstract that away. It's still misleading to have that in autocomplete, but I guess that is due to the fact that the same interface is used by different db providers, and migration file/code even doesn't know which driver will run.
