### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '#props') if destructuring SelectQueryBuilder

### ISSUE THREAD

**Issue by tkovis** [kysely-org/kysely#1135]
When destructuring a SelectQueryBuilder, eg. in an $if func, you can end up with a TypeError uncaught by typescript.

Example code:
```ts
import { db } from "./database";

try {
  const { sql } = db
    .selectFrom("person")
    //.$if(true, (eb) => eb.where("first_name", "=", "John")) // works ok
    .$if(true, ({ where }) => where("first_name", "=", "John")) // throws error
    .compile();
  console.log(sql);
} catch (e) {
  console.log(e);
}
```

Example error:
```
TypeError: Cannot read properties of undefined (reading '#props')
    at where (/path/to/kysely-repro/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:39:21)
    at /path/to/kysely-repro/dist/index.js:8:35
    at SelectQueryBuilderImpl.$if (/path/to/kysely-repro/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:285:20)
    at Object.<anonymous> (/path/to/kysely-repro/dist/index.js:8:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

Tried to research if I am just misunderstanding something, but could not come up with anything.

Example repro here: https://github.com/tkovis/kysely-repro

**Comment by igalklebanov** [comment]
Hey 👋

Don't destructure it.

**Comment by koskimas** [comment]
This has come up so often that maybe we need to consider making all query builders destructible.

**Comment by charllie** [comment]
@igalklebanov this has been marked as intended, but what is the reason behind this?

**Comment by igalklebanov** [comment]
@charllie 

> Hey 👋
> 
> Don't destructure it.
