### ISSUE TITLE
Count returns undefined

### ISSUE THREAD

**Issue by wildfiremedia** [kysely-org/kysely#1150]
In raw queeries, postcount will return 0 but db.fn.count() is return `undefined`. Is there other way I can simplify the code?

```
const persons = await db
    .selectFrom('users as u')
    .innerJoin('post', 'authorId', 'u.id')
    .where('name', '=', 'hello1')
    .where('email', '=', 'asd1@asd.com')
    .groupBy(['u.email', 'u.id'])
    .select([
        'u.id', 'u.name',
        db.fn.count('post.id').as('postcount'),
    ])
    .execute();
```

**Comment by koskimas** [comment]
I don't really understand your issue, but your example code seems to work perfectly, and there's no `undefined` anywhere. https://kyse.link/EMlkE

If your issue is about the wide type given to `postcount`, you can specify narrower type like this:

```ts
db.fn.count<number>('post.id').as('postcount'),
```

**Comment by wildfiremedia** [comment]
Sorry, to update, the query appear to return `undefined` for users, you can see the difference between pg-promise and kysely.

```
try {
    const users = await db3.any(`
SELECT u.id, u.name, COUNT(p.id) as postcount
FROM users u
LEFT JOIN post p ON u.id = p."authorId" 
WHERE u.name = $(name) AND u.email = $(email)
GROUP BY u.id, u.name;
    `, {name: 'hello1', email: 'asd1@asd.com'});
    
    console.log('--' , users[0])
// Output
// -- { id: 2, name: 'hello1', postcount: '0' }


    const persons = await db
    .selectFrom('users as u')
    .innerJoin('post', 'authorId', 'u.id')
    .where('name', '=', 'hello1')
    .where('email', '=', 'asd1@asd.com')
    .groupBy(['u.email', 'u.id'])
    .select([
        'u.id', 'u.name',
        db.fn.count<number>('post.id').as('postcount'),
    ])
    .execute();

// Output
// >>> []

    console.log('>>>', persons)

} catch(e) {
    // error
}


```

**Comment by wildfiremedia** [comment]
db.ts:
```
import { Kysely, PostgresDialect } from 'kysely';
import type { DB } from 'kysely-codegen';
import pkg from 'pg';
const {Pool} = pkg;


export const db = new Kysely<DB>({
  dialect: new PostgresDialect({
    pool: new Pool({
      connectionString: import.meta.env.DATABASE_URL,
    }),
  }),
});
```

**Comment by wildfiremedia** [comment]
When I rename to `post as p`

```
const persons = await db
    .selectFrom('users as u')
    .innerJoin('post as p', 'u.id', 'p.authorId')
    .where('u.name', '=', 'hello1')
    .where('u.email', '=', 'asd1@asd.com')
    .groupBy(['u.id', 'u.email'])
    .select([
        'u.id', 'u.name',
        db.fn.count<number>('post.id').as('postcount'),
    ])
    .execute();

    console.log('>>>', persons)
```

error output

````
error: invalid reference to FROM-clause entry for table "post"
    at /Users/s/Documents/book2/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresConnection.executeQuery (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:69:28)
    at async file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
    at async DefaultConnectionProvider.provideConnection (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
    at async DefaultQueryExecutor.executeQuery (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
    at async SelectQueryBuilderImpl.execute (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/query-builder/select-query-builder.js:315:24)
    at async eval (/Users/s/Documents/book2/src/pages/index.astro:25:21)
    at async callComponentAsTemplateResultOrResponse (file:///Users/s/Documents/book2/node_modules/astro/dist/runtime/server/render/astro/render.js:90:25)
    at async renderToAsyncIterable (file:///Users/s/Documents/book2/node_modules/astro/dist/runtime/server/render/astro/render.js:132:26)
    at PostgresConnection.executeQuery (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:89:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
    at async DefaultConnectionProvider.provideConnection (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
    at async DefaultQueryExecutor.executeQuery (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
    at async SelectQueryBuilderImpl.execute (file:///Users/s/Documents/book2/node_modules/kysely/dist/esm/query-builder/select-query-builder.js:315:24)
    at async eval (/Users/s/Documents/book2/src/pages/index.astro:25:21)
    at async callComponentAsTemplateResultOrResponse (file:///Users/s/Documents/book2/node_modules/astro/dist/runtime/server/render/astro/render.js:90:25)
    at async renderToAsyncIterable (file:///Users/s/Documents/book2/node_modules/astro/dist/runtime/server/render/astro/render.js:132:26)
    at async renderPage (file:///Users/s/Documents/book2/node_modules/astro/dist/runtime/server/render/page.js:31:24) {
  length: 181,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: 'Perhaps you meant to reference the table alias "p".',
  position: '36',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3615',
  routine: 'errorMissingRTE'
}

```
