### ISSUE TITLE
Multiple ConnectionError with MSSQL

### ISSUE THREAD

**Issue by y-wertz-priomold** [kysely-org/kysely#1283]
I'm currently testing stability of my node app with kysely and getting strange behaviour when connection to my mssql database has errors.

For example when I cange my database user or password (to wrong credentials) I'm getting hundreds of connection errors:

```
ConnectionError: Fehler bei der Anmeldung für den Benutzer "prio".
    at Login7TokenHandler.onErrorMessage (C:\Yannik\ENTWICKLUNG\pips-2024\pips-backend\node_modules\tedious\src\token\handler.ts:266:19)
    at Readable.<anonymous> (C:\Yannik\ENTWICKLUNG\pips-2024\pips-backend\node_modules\tedious\src\token\token-stream-parser.ts:23:55)
    at Readable.emit (node:events:514:28)
    at Readable.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
    at Readable.push (node:internal/streams/readable:376:5)
    at next (node:internal/streams/from:98:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ELOGIN'
}
```

Similar behaviour when I screw up my IP adress (from 192.168.21.146 to 192.168.21.1466 (I know this is bs and invalid))

```
ConnectionError: Failed to connect to 192.168.21.1466:1433 - getaddrinfo ENOTFOUND 192.168.21.1466
    at Connection.socketError (C:\Yannik\ENTWICKLUNG\pips-2024\pips-backend\node_modules\tedious\src\connection.ts:2334:28)
    at C:\Yannik\ENTWICKLUNG\pips-2024\pips-backend\node_modules\tedious\src\connection.ts:2123:37
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ESOCKET',
  [cause]: Error: getaddrinfo ENOTFOUND 192.168.21.1466
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: '192.168.21.1466'
  }
}
```
Both errors are just printed, not thrown.

This second case is unlikly (up to impossible) in production. But the first case (database user login credentials change) is possible.

It doesn't crash the app completly, but because this error repeats very often (for a single query) is freezes the application..

My config looks like following:

``` typescript
const dialect = new MssqlDialect({
  tarn: {
    ...tarn,
    options: {
      min: 0,
      max: 10,
    },
  },
  tedious: {
    ...tedious,
    connectionFactory: () =>
      new tedious.Connection({
        authentication: {
          options: {
            password: config.SOU_PASSWORD,
            userName: config.SOU_USER,
          },
          type: "default",
        },
        options: {
          database: config.SOU_DATABASE,
          port: 1433,
          trustServerCertificate: true,
          maxRetriesOnTransientErrors: 0,
          connectTimeout: 1000,
          requestTimeout: 1000,
        },
        server: config.SOU_HOST,
      }),
  },
});

export const db = new Kysely<DB>({
  dialect: dialect,
});
```

And my query look like following:

``` typescript
const sqlResultAuftragseingang = await db
    .selectFrom("AuftragPos")
    // is reality here is a working query
    .executeTakeFirst()
    .catch((err) => err as Error);

  // Guard further execution
  if (isError(sqlResultAuftragseingang)) {
    // log error to console and send to client
    sendError(sqlResultAuftragseingang)
  }
```

Even if the Timeout is set to a short amount of time and retries is set to zero, it seems to retry very often until the Promise from Kyselys `execute()` Function resolves with an error.

#### Expected behaviour
After timeout or on connection error the `execute()` promise resolves instantly with an error, without blocking a long time before resolving the promise.

Am I doing something wrong in my config or is this a bug?

Thanks!

**Comment by belgattitude** [comment]
I tracked it down to tarn, you can try with `propagateCreateError` to `true` which will throw immediatly. 

I don't recommended to set it to true in production. (see question below)

```typescript
const dialect = new MssqlDialect({
  tarn: {
    ...Tarn,
    options: {
      min: 0,
      max: 10,
     // 👉 https://github.com/vincit/tarn.js?tab=readme-ov-file#usage
      propagateCreateError: true
    },
  },
})
```

In the mssql driver, the option is set to true by default: https://github.com/search?q=repo%3Atediousjs%2Fnode-mssql%20propagateCreateError&type=code. But I couldn't find code that would handle retries (max, etc) 

In an older version they supported it, but reverted to let tarn do it (see [changelog](https://github.com/tediousjs/node-mssql/blob/master/CHANGELOG.txt)).

> [removed] Backoff try strategy for creating connections removed, `tarn.js` built-in retry strategy used instead

I tried different tarn options (createRetryIntervalMiddles, createTimeoutMillis, new validationConnections) but seems when propagateCreateError is set to true, it immediately throws. So there isn't a way to properly retry.

Question ? Is there a way in kysely to add retry on connection error (ie with p-retry...)

**Comment by belgattitude** [comment]
Sorry I’ve been too quick to answer… my error was a bit different. I’ll have a deeper look.

**Comment by buildtheui** [comment]
@belgattitude did you find another safe solution for this?

**Comment by igalklebanov** [comment]
Does it still occur?

https://github.com/kysely-org/kysely/pull/1463 might have resolved it.
