### ISSUE TITLE
inner join error

### ISSUE THREAD

**Issue by mrtornado** [kysely-org/kysely#405]
``` javascript
    const result = await db.with("config_query", (qb) =>
        qb
          .selectFrom("config_proxy")
          .whereRef("config_proxy.config_key", "=", "config.config_key")
          .whereExists((qb) =>
            qb.selectFrom("cblock_ip")
              .whereRef("cblock_ip.ip_key", "=", "config_proxy.ip_key")
              .where("cblock_ip.ip_key", "=", "[ip_key]")
          ))
        .selectFrom("config")
        .whereExists((qb) => qb.selectFrom("config_query").select(1))
        .execute();
```

why is this not working , I understand that InnerJoin doesn't work with mysql but still I'm getting : 

```
An error occurred during route handling or page rendering. Error: not implemented
    at parseJoin (https://cdn.jsdelivr.net/npm/kysely/dist/esm/parser/join-parser.js:14:15)
    at SelectQueryBuilder.innerJoin (https://cdn.jsdelivr.net/npm/kysely/dist/esm/query-builder/select-query-builder.js:279:71)
```

what I'm doing wrong, or what can I do to select some fields from `cblock_ip.ip_key` , so basically I have `config` that connects to `config_proxy` trough `config_key` , and `config_proxy` that connects to `cblock_ip` trough `ip_key`

btw I'm using MySql

**Comment by mrtornado** [comment]
nvm, I'm rtarded, I had another innerJoin() on another sql query in the same page. A left over from when I tried to use innerJoin . ... sry for the troubles

**Comment by koskimas** [comment]
Just curious: are you using Kysely without typescript? There's multiple things in your query above that shouldn't compile, like `.select(1)` in the latter subquery.

**Comment by mrtornado** [comment]
Nope, I'm using it with typescript but didn't got to that part when I posted this message, I was still stuck on the innerJoin part :) I mange to do the query but I did it like this: 
 ```javascript
   const configs = await db
        .selectFrom("config")
        .where("config_name", "=", link)
        .selectAll("config")
        .execute();

      const proxyResult = await db
        .selectFrom("config_proxy")
        .where("config_proxy.config_key", "=", configs[0].config_key)
        .selectAll()
        .execute();

      const ipAddresses = [];
      for (const proxy of proxyResult) {
        const ipResult = await db
          .selectFrom("cblock_ip")
          .where("cblock_ip.ip_key", "=", proxy.ip_key)
          .select("cblock_ip.ip_address")
          .execute();

        if (ipResult.length > 0) {
          ipAddresses.push(`${ipResult[0].ip_address}:${proxy.ip_port}`);
        }
      }
```
      
      but yea that's a pain when it I have like 300+ results for ip_address , I tried doing it with map and promise but the that seems mysql driver doesn't limit the connections well enough, one other thing I could do to make it work with map was to increase the mysql connections limit on my server 1000, that seemed to be working but yea only 4 gb of ram, doesn't seem to be enough for 1000 connections. Isn't there a better way to do this ? maybe I could use like plain SQL ?

**Comment by koskimas** [comment]
You can do all that in a single query. Here's a simple two-line change that already drops the queries down to three: 

```ts
const configs = await db
  .selectFrom("config")
  .where("config_name", "=", link)
  .selectAll("config")
  .execute();

const proxyResult = await db
  .selectFrom("config_proxy")
  .where("config_proxy.config_key", "=", configs[0].config_key)
  .selectAll()
  .execute();

const ipResult = await db
  .selectFrom("cblock_ip")
  .where("cblock_ip.ip_key", "in", proxyResult.map(it => it.ip_key))
  .select("cblock_ip.ip_address")
  .execute();
  
if (ipResult.length > 0) {
  ipAddresses.push(`${ipResult[0].ip_address}:${proxy.ip_port}`);
}
```

**Comment by koskimas** [comment]
Here's all of it in one query:

```ts
const result = await db
  .with("config", qb => qb
    .selectFrom("config")
    .selectAll()
    .where("config_name", "=", link)
  .with("proxy", qb => qb
    .selectFrom("config_proxy")
    .selectAll()
    .where("config_proxy.config_key", "in", qb.selectFrom("config").select("config_key"))
  .selectFrom("cblock_ip")
  .where("cblock_ip.ip_key", "in", (eb) => eb.selectFrom("proxy").select("ip_key"))
  .select("cblock_ip.ip_address")
  .execute();
```

**Comment by mrtornado** [comment]
thanks a lot , just the first one where you change it to 3 queries was enough, but thanks for taking the time to write them, I have something to play with now :)

**Comment by mrtornado** [comment]
So one more quick question if you don't mind, I tried to build a query like this one:   

```javascript
  const result = await db
      .with("user_result", (qb) =>
        qb
          .selectFrom("member")
          .select("member_key")
          .where("member_key", "=", user))
      .selectFrom("member_social")
      .where(
        "member_social.member_key",
        "in",
        (eb) => eb.selectFrom("user_result").select("member_key"),
      )
      .select("member_social.avatar_url")
      .execute();
```
The error I get is: 
```
500 internal error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`user_result` as (select `member_key` from `member` where `member_key` = "9770")' at line 1
;
```
This means that mysql doesn't support this type of query right and I have to do them one by one right ?
