### ISSUE TITLE
`Error: invalid immediate value [object Object]`

### ISSUE THREAD

**Issue by Jazcash** [kysely-org/kysely#538]
This error started happening when I added a dependency (my own utils lib) that contains a kysely plugin. I first thought the issue was because that project compiled to CJS and my main project is ESM, and I found [this thread](https://github.com/kysely-org/kysely/issues/343) that suggests having 2 different instances/versions can cause the issue. However I've now removed that dependency, `rm -rf node_modules package-lock.json && npm i`, cleaned my `dist` and tried again, but I'm still getting the same error:

```
file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:1019
            throw new Error(`invalid immediate value ${value}`);        
                  ^

Error: invalid immediate value [object Object]
    at SqliteQueryCompiler.appendImmediateValue (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:1019:19)
    at SqliteQueryCompiler.visitValue (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:261:18)
    at SqliteQueryCompiler.visitNode (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:93:34)
    at SqliteQueryCompiler.visitDefaultValue (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:817:14)
    at SqliteQueryCompiler.visitNode (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:93:34)
    at SqliteQueryCompiler.visitColumnDefinition (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:366:18)
    at SqliteQueryCompiler.visitNode (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:93:34)
    at SqliteQueryCompiler.compileList (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:116:18)
    at SqliteQueryCompiler.visitCreateTable (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:338:14)
    at SqliteQueryCompiler.visitNode (file:///C:/Users/jaspe/Repos/tachyon-server-ts/node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:93:34)

Node.js v18.16.0
```

Any ideas?

**Comment by koskimas** [comment]
You still have two or more versions. That's the only way this can happen. One of the versions is also very old. We've implemented a workaround that supports different versions in this particular case a while ago.

**Comment by Jazcash** [comment]
Nevermind, that's a red herring. I found it's because of this line in my project:

`.addColumn("test", "json", (col) => col.notNull().defaultTo([]))`

Should be ` .addColumn("test", "json", (col) => col.notNull().defaultTo('[]'))`
