### ISSUE TITLE
Problem running sample migration script

### ISSUE THREAD

**Issue by billtlee** [kysely-org/kysely#584]
Hi,

I am trying to play with the migration script to work with PlanetScale but am having problems.  Does any know what might be causing the issue:

```
import * as path from 'path';
import { PlanetScaleDialect } from 'kysely-planetscale';
import { promises as fs } from 'fs';
import {
  Kysely,
  Migrator,
  FileMigrationProvider
} from 'kysely';
import { Database } from './types';

async function migrateToLatest() {
  const db = new Kysely<Database>({
    dialect: new PlanetScaleDialect({
      url: process.env.DATABASE_URL
    })
  });

  const migrator = new Migrator({
    db,
    provider: new FileMigrationProvider({
      fs,
      path,
      // This needs to be an absolute path.
      migrationFolder: path.join(__dirname, 'migrations/migrations')
    })
  });

  const { error, results } = await migrator.migrateToLatest();

  results?.forEach((it) => {
    if (it.status === 'Success') {
      console.log(`migration "${it.migrationName}" was executed successfully`);
    } else if (it.status === 'Error') {
      console.error(`failed to execute migration "${it.migrationName}"`);
    }
  });

  if (error) {
    console.error('failed to migrate');
    console.error(error);
    process.exit(1);
  }

  await db.destroy();
}

migrateToLatest();
```

```
npx ts-node database/migrateToLatest.ts 
/Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/node_modules/kysely-planetscale/dist/index.js from /Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/database/migrateToLatest.ts not supported.
Instead change the require of index.js in /Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/database/migrateToLatest.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/node_modules/ts-node/dist/index.js:851:20)
    at /Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/database/migrateToLatest.ts:70:103 {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by igalklebanov** [comment]
Hey 👋 

`@planetscale/database` ships as ESM only (https://github.com/planetscale/database-js/issues/122), try setting `"type": "module"` in your package.json.

**Comment by billtlee** [comment]
@igalklebanov Thanks for the reply!  If I add "type": "module" in package.json, I get 
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/bill/Documents/MyProjects/nextjs-planetscale-nextauth-tailwindcss-template/database/migrateToLatest.ts`

**Comment by igalklebanov** [comment]
Seems like you're importing or trying to run a `.ts` file, which usually (outside of deno) requires compilation.

**Comment by billtlee** [comment]
sorry, what's deno?
