### ISSUE TITLE
Offset method giving an error in SQLite DB.

### ISSUE THREAD

**Issue by hkvongit** [kysely-org/kysely#688]
While using offset method it is giving an error like below:
```bash
/Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/better-sqlite3@8.6.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5
	return this[cppdb].prepare(sql, this, false);
                    ^
SqliteError: near "?": syntax error
    at Database.prepare (/Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/better-sqlite3@8.6.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at SqliteConnection.executeQuery (/Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/kysely@0.26.3/node_modules/kysely/dist/cjs/dialect/sqlite/sqlite-driver.js:53:31)
    at /Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/kysely@0.26.3/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:37:45
    at DefaultConnectionProvider.provideConnection (/Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/kysely@0.26.3/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DefaultQueryExecutor.executeQuery (/Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/kysely@0.26.3/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:36:16)
    at async SelectQueryBuilderImpl.execute (/Users/harikrishnanv/Documents/odessey-projects/INTERNAL-PROJECTS/nibbles-logtrack/server/node_modules/.pnpm/kysely@0.26.3/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:295:24) {
  code: 'SQLITE_ERROR'
}
```
Program code:
```ts
const dbDocs = await db.selectFrom('project').selectAll().limit(10).offset(10).execute()
```

Rest everything is working fine.

**Comment by AlexErrant** [comment]
What's the generated SQL? I have a helper method like this

```ts
export function log<T extends Compilable>(qb: T): T {
	console.log('Query : ', qb.compile().query)
	console.log('SQL   : ', qb.compile().sql)
	console.log('Params: ', qb.compile().parameters)
	return qb
}
```
which you can invoke like

```ts
const dbDocs = await db.selectFrom('project').selectAll().limit(10).offset(10).$call(log).execute()
```

FWIW I'm using limit/offset [here](https://github.com/AlexErrant/Pentive/blob/main/app/src/sqlite/card.ts#L208-L209), and it's given me no problems (other than bad performance on 10k+ offset... in the middle of implementing a fix by (trying to) use temp tables and rowids 🤪 sadly can't use cursor pagination).

**Comment by koskimas** [comment]
According to our test suite, it works perfectly.

**Comment by hkvongit** [comment]
Thanks @AlexErrant for your help. Was able to log the query using the code you gave `const dbDocs = await db.selectFrom('project').selectAll().limit(10).offset(10).$call(log).execute()`. The issue was related to my query generator, the limit was not setting properly, so the error was coming.

Generated Query:
```bash
SQL   :  select * from "project" offset ?
Params:  [ 1 ]
```
After fix of my code:
```bash
SQL   :  select * from "project" limit ? offset ?
Params:  [ 10, 1 ]
```
