### ISSUE TITLE
"Connection terminated unexpectedly"

### ISSUE THREAD

**Issue by cainus** [kysely-org/kysely#745]
I'm getting the above exception intermittently from a long-running script (via `setInterval()`), usually within a couple of minutes and sometimes immediately.

My Kysely setup seems pretty vanilla:

```typescript
const dialect = new PostgresDialect({
  pool: new Pool({
    database: process.env.DATABASE_NAME,
    host: process.env.DATABASE_HOST,
    password: process.env.DATABASE_PASSWORD,
    user: process.env.DATABASE_USER,
    port: process.env.DATABASE_PORT ? parseInt(process.env.DATABASE_PORT) : 5432,
    })
 })
 ```
 
It works intermittently so there's no problem with the credentials.  The same config works without exceptions in a web server process as well.
 
Here's the stack trace I'm seeing:
 
```
{PATH}/node_modules/pg/lib/client.js:132
      const error = this._ending ? new Error('Connection terminated') : new Error('Connection terminated unexpectedly')
                                                                        ^
Error: Connection terminated unexpectedly
    at Connection.<anonymous> ({PATH}/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:628:28)
    at Connection.emit (node:events:514:28)
    at Connection.emit (node:domain:489:12)
    at Socket.<anonymous> ({PATH}/node_modules/pg/lib/connection.js:63:12)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:337:12)
make: *** [Makefile:6: refresh-cache] Error 1
``` 
 
Thanks for any guidance!

**Comment by koskimas** [comment]
Kysely delegates all communication to to underlying driver. The same thing would happen if you didn't use kysely at all but the pool instance directly.
