### ISSUE TITLE
Streaming results not working on Deno for PostgreSQL

### ISSUE THREAD

**Issue by will-weiss** [kysely-org/kysely#866]
Hello! I'm finding I'm unable to `.stream()` results on Deno when the same query works via `.execute()`

That is, this works

```typescript
const results = await db.selectFrom('conditions')
  .where('info_link_href', 'is not', null)
  .select(['info_link_href', 'name', 'id'])
  .execute()
```

but this doesn't

```typescript
const stream = await db.selectFrom('conditions')
  .where('info_link_href', 'is not', null)
  .select(['info_link_href', 'name', 'id'])
  .stream()
  
for await (const condition of stream) {
  console.log(condition)
}
```

with error

```
error: Uncaught (in promise) TypeError: connection.streamQuery(...) is not a function or its return value is not async iterable
            for await (const result of connection.streamQuery(compiledQuery, chunkSize)) {
                                                  ^
    at DefaultQueryExecutor.stream (https://cdn.jsdelivr.net/npm/kysely/dist/esm/query-executor/query-executor-base.js:52:51)
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async SelectQueryBuilderImpl.stream (https://cdn.jsdelivr.net/npm/kysely/dist/esm/query-builder/select-query-builder.js:315:26)
    at async file:///Users/willweiss/dev/morehumaninternet/virtual-hospitals-africa/scripts/scrape-nih.ts:9:18
```

My imports are as follows

```
{
  "kysely": "https://cdn.jsdelivr.net/npm/kysely/dist/esm/index.js",
  "kysely/": "https://cdn.jsdelivr.net/npm/kysely/dist/esm/",
  "kysely-deno-postgres": "https://deno.land/x/kysely_deno_postgres@v0.4.0/mod.ts"
}
```

while my database is defined as follows

```typescript
import {
  Kysely,
  PostgresAdapter,
  PostgresIntrospector,
  PostgresQueryCompiler,
} from 'kysely'
import { PostgreSQLDriver } from 'kysely-deno-postgres'
import { DatabaseSchema } from '../types.ts'

const db = new Kysely<DatabaseSchema>({
  dialect: {
    createAdapter() {
      return new PostgresAdapter()
    },
    createDriver() {
      return new PostgreSQLDriver(Deno.env.get('DATABASE_URL')!) as any
    },
    createIntrospector(db: Kysely<unknown>) {
      return new PostgresIntrospector(db)
    },
    createQueryCompiler() {
      return new PostgresQueryCompiler()
    },
  },
})

export default db
```

Thanks in advance!

**Comment by garymathews** [comment]
It looks like you are awaiting twice, remove the first _await_.
```ts
const stream = await db.selectFrom('conditions')
               ^
```

**Comment by igalklebanov** [comment]
Hey 👋 

You're using a community dialect, that might have not implemented properly (or at all) the streaming method. We do not maintain this dialect, so you best submit an issue in its repository.
